import type { RolePermissions } from "@/types/db"

// Helper to create permissions with all false by default
function createPermissions(overrides: Partial<RolePermissions> = {}): RolePermissions {
  return {
    canViewDashboard: false,
    canManageUsers: false,
    canManageFranchises: false,
    canManageRoles: false,
    canViewAllFranchises: false,
    canManageInventory: false,
    canApproveInventoryTransfers: false,
    canManageFinance: false,
    canAssignLoanOptions: false,
    canUploadDueLetters: false,
    canGenerateInvoices: false,
    canVerifyCashDeposits: false,
    canManageExpenses: false,
    canApproveExpenses: false,
    canProcessSalary: false,
    canManageTransport: false,
    canCreateTrips: false,
    canManageMarketing: false,
    canViewReports: false,
    canExportReports: false,
    canViewAuditLogs: false,
    canConfigureSystem: false,
    canCreateLeads: false,
    canViewOwnLeads: false,
    canViewAllLeads: false,
    canReassignLeads: false,
    canUploadDocuments: false,
    canSelectLoanOption: false,
    canUploadCashDeposit: false,
    canManageFranchiseLeads: false,
    canCreateFranchiseDeals: false,
    canVerifyFranchisePayments: false,
    canCreateTickets: false,
    canManageTickets: false,
    ...overrides,
  }
}

// All permissions set to true for superadmin
const allPermissions = createPermissions({
  canViewDashboard: true,
  canManageUsers: true,
  canManageFranchises: true,
  canManageRoles: true,
  canViewAllFranchises: true,
  canManageInventory: true,
  canApproveInventoryTransfers: true,
  canManageFinance: true,
  canAssignLoanOptions: true,
  canUploadDueLetters: true,
  canGenerateInvoices: true,
  canVerifyCashDeposits: true,
  canManageExpenses: true,
  canApproveExpenses: true,
  canProcessSalary: true,
  canManageTransport: true,
  canCreateTrips: true,
  canManageMarketing: true,
  canViewReports: true,
  canExportReports: true,
  canViewAuditLogs: true,
  canConfigureSystem: true,
  canCreateLeads: true,
  canViewOwnLeads: true,
  canViewAllLeads: true,
  canReassignLeads: true,
  canUploadDocuments: true,
  canSelectLoanOption: true,
  canUploadCashDeposit: true,
  canManageFranchiseLeads: true,
  canCreateFranchiseDeals: true,
  canVerifyFranchisePayments: true,
  canCreateTickets: true,
  canManageTickets: true,
})

export const systemRoles = [
  {
    name: "superadmin",
    displayName: "Super Admin",
    description: "System owner with unrestricted access and configuration authority",
    isSystemRole: true,
    permissions: allPermissions,
  },
  {
    name: "ho_finance",
    displayName: "HO Finance",
    description: "Handles loan processing, financer coordination, and due-letter management",
    isSystemRole: true,
    permissions: createPermissions({
      canViewDashboard: true,
      canManageFinance: true,
      canAssignLoanOptions: true,
      canUploadDueLetters: true,
      canViewReports: true,
      canViewAllFranchises: true,
    }),
  },
  {
    name: "ho_accounts",
    displayName: "HO Accounts",
    description: "Responsible for financial verification, invoicing, expense approvals, and payouts",
    isSystemRole: true,
    permissions: createPermissions({
      canViewDashboard: true,
      canGenerateInvoices: true,
      canVerifyCashDeposits: true,
      canManageExpenses: true,
      canApproveExpenses: true,
      canProcessSalary: true,
      canViewReports: true,
      canExportReports: true,
      canViewAllFranchises: true,
      canVerifyFranchisePayments: true,
    }),
  },
  {
    name: "ho_inventory",
    displayName: "HO Inventory",
    description: "Central authority for inventory control and stock movement",
    isSystemRole: true,
    permissions: createPermissions({
      canViewDashboard: true,
      canManageInventory: true,
      canApproveInventoryTransfers: true,
      canViewAllFranchises: true,
      canViewReports: true,
    }),
  },
  {
    name: "ho_sales",
    displayName: "HO Sales (FDM)",
    description: "Franchise Development Manager - handles franchise sales and onboarding",
    isSystemRole: true,
    permissions: createPermissions({
      canViewDashboard: true,
      canManageFranchiseLeads: true,
      canCreateFranchiseDeals: true,
      canUploadDocuments: true,
      canViewReports: true,
    }),
  },
  {
    name: "ho_transport",
    displayName: "HO Transport",
    description: "Executes physical movement of vehicles and inventory",
    isSystemRole: true,
    permissions: createPermissions({
      canViewDashboard: true,
      canManageTransport: true,
      canCreateTrips: true,
      canViewAllFranchises: true,
    }),
  },
  {
    name: "ho_hr",
    displayName: "HO HR",
    description: "Manages people, incentives, salaries, franchises, and support tickets",
    isSystemRole: true,
    permissions: createPermissions({
      canViewDashboard: true,
      canManageUsers: true,
      canManageFranchises: true,
      canProcessSalary: true,
      canManageTickets: true,
      canReassignLeads: true,
      canViewAllFranchises: true,
      canViewReports: true,
      canExportReports: true,
    }),
  },
  {
    name: "ho_marketing",
    displayName: "HO Marketing",
    description: "Handles marketing expenses and campaigns",
    isSystemRole: true,
    permissions: createPermissions({
      canViewDashboard: true,
      canManageMarketing: true,
      canManageExpenses: true,
      canViewReports: true,
    }),
  },
  {
    name: "franchise_owner",
    displayName: "Franchise Owner",
    description: "Business owner of an individual franchise",
    isSystemRole: true,
    permissions: createPermissions({
      canViewDashboard: true,
      canViewOwnLeads: true,
      canViewAllLeads: true,
      canReassignLeads: true,
      canViewReports: true,
      canCreateTickets: true,
    }),
  },
  {
    name: "franchise_salesperson",
    displayName: "Franchise Salesperson",
    description: "Staff salesperson at franchise location",
    isSystemRole: true,
    permissions: createPermissions({
      canViewDashboard: true,
      canCreateLeads: true,
      canViewOwnLeads: true,
      canUploadDocuments: true,
      canSelectLoanOption: true,
      canUploadCashDeposit: true,
      canCreateTickets: true,
    }),
  },
  {
    name: "franchise_godown",
    displayName: "Franchise Godown",
    description: "Manages physical inventory at franchise locations",
    isSystemRole: true,
    permissions: createPermissions({
      canViewDashboard: true,
      canManageInventory: true,
      canCreateTickets: true,
    }),
  },
  {
    name: "franchise_mechanic",
    displayName: "Franchise Mechanic",
    description: "Handles repair and maintenance work",
    isSystemRole: true,
    permissions: createPermissions({
      canViewDashboard: true,
      canCreateTickets: true,
    }),
  },
]

export default systemRoles

